# Generated by Django 4.2.3 on 2023-07-25 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0003_rename_text_exercise_code_exercise_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_exercise', models.IntegerField(default=0, verbose_name='Bajargan vazifalar soni')),
                ('exercise_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercisecategory', verbose_name='Vazifa turi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
