# Generated by Django 4.2.3 on 2023-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='exercise_id',
            field=models.TextField(default=0, verbose_name='Tugatgan vazifalar id lari'),
            preserve_default=False,
        ),
    ]
