# Generated by Django 4.2.3 on 2023-07-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_exercise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completed_exercise',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bajargan vazifalar soni'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='exercise_id',
            field=models.TextField(blank=True, null=True, verbose_name='Tugatgan vazifalar id lari'),
        ),
    ]
