# Generated by Django 4.2.3 on 2023-07-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_progress_completed_exercise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='exercise_id',
            new_name='exercise_ids',
        ),
    ]
