# Generated by Django 4.2.3 on 2023-07-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_rename_exercise_id_progress_exercise_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completed_exercise',
            field=models.IntegerField(default=0, verbose_name='Bajargan vazifalar soni'),
        ),
    ]
