# Generated by Django 4.2.4 on 2023-08-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_alter_progress_completed_exercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Progres', 'verbose_name_plural': 'Progreslar'},
        ),
    ]
