# Generated by Django 4.2.3 on 2023-07-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0002_alter_exercise_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='text',
            new_name='code',
        ),
        migrations.AddField(
            model_name='exercise',
            name='answer',
            field=models.TextField(default=1, verbose_name='Exercise answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='question',
            field=models.TextField(default=1, verbose_name='Exercise question'),
            preserve_default=False,
        ),
    ]
