# Generated by Django 4.2.3 on 2023-07-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursechapter',
            name='jupyter_link',
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='chapter_content_ipynb',
            field=models.FileField(default='me', upload_to='ipynb_notebooks/'),
            preserve_default=False,
        ),
    ]
