# Generated by Django 4.2.3 on 2023-07-22 09:15

from django.db import migrations, models
import learn.convert


class Migration(migrations.Migration):
    dependencies = [
        ('learn', '0002_remove_coursechapter_jupyter_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechapter',
            name='chapter_content_ipynb',
            field=models.FileField(upload_to='ipynb_notebooks/', validators=[learn.convert.is_ipynb]),
        ),
    ]
